export const JapaneseColorQuestions = [
  {
    prompt: "Which of these means the color green in Japanese?",
    optionA: "白い (Shiroi)",
    optionB: "緑 (Midori)",
    optionC: "黒 (Kuro)",
    optionD: "赤 (Aka)",
    answer: "B",
    word: "緑 (Midori) = Green",
  },
  {
    prompt: "Which of these means the color yellow in Japanese?",
    optionA: "黄色 (Kiiro)",
    optionB: "黒 (Kuro)",
    optionC: "紫の (Murasakino)",
    optionD: "緑 (Midori)",
    answer: "A",
    word: "黄色 (Kiiro) = Yellow",
  },
  {
    prompt: "Which of these means the color black in Japanese?",
    optionA: "黒 (Kuro)",
    optionB: "紫の (Murasakino)",
    optionC: "白い (Shiroi)",
    optionD: "青い (Aoi)",
    answer: "A",
    word: "黒 (Kuro) = Black",
  },
  {
    prompt: "Which of these means the color red in Japanese?",
    optionA: "青い (Aoi)",
    optionB: "紫の (Murasakino)",
    optionC: "茶色 (Chairo)",
    optionD: "赤 (Aka)",
    answer: "D",
    word: "赤 (Aka) = Red",
  },
  {
    prompt: "Which of these means the color white in Japanese?",
    optionA: "茶色 (Chairo)",
    optionB: "黄色 (Kiiro)",
    optionC: "白い (Shiroi)",
    optionD: "緑 (Midori)",
    answer: "C",
    word: "白い (Shiroi) = White",
  },
  {
    prompt: "Which of these means the color purple in Japanese?",
    optionA: "赤 (Aka)",
    optionB: "黒 (Kuro)",
    optionC: "茶色 (Chairo)",
    optionD: "紫の (Murasakino)",
    answer: "D",
    word: "紫の (Murasakino) = Purple",
  },
  {
    prompt: "Which of these means the color blue in Japanese?",
    optionA: "青い (Aoi)",
    optionB: "黄色 (Kiiro)",
    optionC: "白い (Shiroi)",
    optionD: "黒 (Kuro)",
    answer: "A",
    word: "青い (Aoi) = Blue",
  },
  {
    prompt: "Which of these means the color brown in Japanese?",
    optionA: "紫の (Murasakino)",
    optionB: "茶色 (Chairo)",
    optionC: "緑 (Midori)",
    optionD: "青い (Aoi)",
    answer: "B",
    word: "茶色 (Chairo) = Brown",
  },
];

export const JapaneseTransportationsQuestions = [
  {
    prompt: "Which of these is the word car in Japanese?",
    optionA: "自転車 (Jitensha)",
    optionB: "飛行機 (Hikōki)",
    optionC: "車 (Kuruma)",
    optionD: "ヘリコプター (Herikoputā)",
    answer: "C",
    word: "車 (Kuruma) = Car",
  },
  {
    prompt: "Which of these is the word motorbike in Japanese?",
    optionA: "バイク (Baiku)",
    optionB: "ヘリコプター (Herikoputā)",
    optionC: "ボート (Boto)",
    optionD: "飛行機 (Hikōki)",
    answer: "A",
    word: "バイク (Baiku) = Motorbike",
  },
  {
    prompt: "Which of these is the word bike in Japanese?",
    optionA: "バイク (Baiku)",
    optionB: "バス (Basu)",
    optionC: "ヨット (Yotto)",
    optionD: "自転車 (Jitensha)",
    answer: "D",
    word: "自転車 (Jitensha) = Bike",
  },
  {
    prompt: "Which of these is the word bus in Japanese?",
    optionA: "ヨット (Yotto)",
    optionB: "ヘリコプター (Herikoputā)",
    optionC: "飛行機 (Hikōki)",
    optionD: "バス (Basu)",
    answer: "D",
    word: "バス (Basu) = Bus",
  },
  {
    prompt: "Which of these is the word plane in Japanese?",
    optionA: "ヘリコプター (Herikoputā)",
    optionB: "飛行機 (Hikōki)",
    optionC: "潜水艦 (Sensuikan)",
    optionD: "バス (Basu)",
    answer: "B",
    word: "飛行機 (Hikōki) = Plane",
  },
  {
    prompt: "Which of these is the word yacht in Japanese?",
    optionA: "訓練 (Kunren)",
    optionB: "ヨット (Yotto)",
    optionC: "バイク (Baiku)",
    optionD: "潜水艦 (Sensuikan)",
    answer: "B",
    word: "ヨット (Yotto) = Yacht",
  },
  {
    prompt: "Which of these is the word helicopter in Japanese?",
    optionA: "ヘリコプター (Herikoputā)",
    optionB: "訓練 (Kunren)",
    optionC: "白い (Shiroi)",
    optionD: "バイク (Baiku)",
    answer: "A",
    word: "ヘリコプター (Herikoputā) = Helicopter",
  },
  {
    prompt: "Which of these is the word train in Japanese?",
    optionA: "潜水艦 (Sensuikan)",
    optionB: "ボート (Boto)",
    optionC: "バイク (Baiku)",
    optionD: "訓練 (Kunren)",
    answer: "D",
    word: "訓練 (Kunren) = Train",
  },
  {
    prompt: "Which of these is the word boat in Japanese?",
    optionA: "ボート (Boto)",
    optionB: "車 (Kuruma)",
    optionC: "訓練 (Kunren)",
    optionD: "潜水艦 (Sensuikan)",
    answer: "A",
    word: "ボート (Boto) = Boat",
  },
  {
    prompt: "Which of these is the word submarine in Japanese?",
    optionA: "ボート (Boto)",
    optionB: "潜水艦 (Sensuikan)",
    optionC: "車 (Kuruma)",
    optionD: "ヨット (Yotto)",
    answer: "A",
    word: "潜水艦 (Sensuikan) = Submarine",
  },
];

export const GermanAnimalsQuestions = [
  {
    prompt: "Which of these means cat in German?",
    optionA: "Kuh",
    optionB: "Hund",
    optionC: "Katze",
    optionD: "Fische",
    answer: "C",
    word: "Katze = Cat",
  },
  {
    prompt: "Which of these means fish in German?",
    optionA: "Fische",
    optionB: "Katze",
    optionC: "Affe",
    optionD: "Hirsch",
    answer: "A",
    word: "Fische = Fish",
  },
  {
    prompt: "Which of these means rabbit in German?",
    optionA: "Hund",
    optionB: "Ente",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "D",
    word: "Hase = Rabbit",
  },
  {
    prompt: "Which of these means dog in German?",
    optionA: "Vogel",
    optionB: "Kamel",
    optionC: "Fische",
    optionD: "Hund",
    answer: "D",
    word: "Hund = Dog",
  },
  {
    prompt: "Which of these means bird in German?",
    optionA: "Kamel",
    optionB: "Ziege",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "C",
    word: "Vogel = Bird",
  },
  {
    prompt: "Which of these means pig in German?",
    optionA: "Katze",
    optionB: "Schwein",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "B",
    word: "Schwein = Pig",
  },
  {
    prompt: "Which of these means duck in German?",
    optionA: "Kamel",
    optionB: "Schwein",
    optionC: "Ente",
    optionD: "Hähnchen",
    answer: "C",
    word: "Ente = Duck",
  },
  {
    prompt: "Which of these means chicken in German?",
    optionA: "Hähnchen",
    optionB: "Schwein",
    optionC: "Hirsch",
    optionD: "Hase",
    answer: "A",
    word: "Hähnchen = Chicken",
  },
  {
    prompt: "Which of these means cow in German?",
    optionA: "Katze",
    optionB: "Kuh",
    optionC: "Ente",
    optionD: "Ziege",
    answer: "B",
    word: "Kuh = Cow",
  },
  {
    prompt: "Which of these means fox in German?",
    optionA: "Hähnchen",
    optionB: "Kuh",
    optionC: "Ente",
    optionD: "Fuchs",
    answer: "D",
    word: "Fuchs = Fox",
  },
  {
    prompt: "Which of these means deer in German?",
    optionA: "Hähnchen",
    optionB: "Hirsch",
    optionC: "Fuchs",
    optionD: "Vogel",
    answer: "B",
    word: "Hirsch = Deer",
  },
];
