export const JapaneseColorQuestions = [
  {
    prompt: "Which of these means the color green in Japanese?",
    optionA: "しろ (Shiro)",
    optionB: "みどり (Midori)",
    optionC: "くろ (Kuro)",
    optionD: "あか (Aka)",
    answer: "B",
    word: "みどり (Midori) = Green",
  },
  {
    prompt: "Which of these means the color yellow in Japanese?",
    optionA: "きいろ (Kiiro)",
    optionB: "くろ (Kuro)",
    optionC: "むらさき (Murasaki)",
    optionD: "みどり (Midori)",
    answer: "A",
    word: "きいろ (Kiiro) = Yellow",
  },
  {
    prompt: "Which of these means the color black in Japanese?",
    optionA: "くろ (Kuro)",
    optionB: "むらさき (Murasaki)",
    optionC: "しろ (Shiro)",
    optionD: "あお (Ao)",
    answer: "A",
    word: "くろ (Kuro) = Black",
  },
  {
    prompt: "Which of these means the color red in Japanese?",
    optionA: "あお (Ao)",
    optionB: "むらさき (Murasaki)",
    optionC: "ちゃいろ (Chairo)",
    optionD: "あか (Aka)",
    answer: "D",
    word: "あか (Aka) = Red",
  },
  {
    prompt: "Which of these means the color white in Japanese?",
    optionA: "ちゃいろ (Chairo)",
    optionB: "きいろ (Kiiro)",
    optionC: "しろ (Shiro)",
    optionD: "みどり (Midori)",
    answer: "C",
    word: "しろ (Shiro) = White",
  },
  {
    prompt: "Which of these means the color purple in Japanese?",
    optionA: "あか (Aka)",
    optionB: "くろ (Kuro)",
    optionC: "ちゃいろ (Chairo)",
    optionD: "むらさき (Murasaki)",
    answer: "D",
    word: "むらさき (Murasaki) = Purple",
  },
  {
    prompt: "Which of these means the color blue in Japanese?",
    optionA: "あお (Ao)",
    optionB: "きいろ (Kiiro)",
    optionC: "しろ (Shiro)",
    optionD: "くろ (Kuro)",
    answer: "A",
    word: "あお (Ao) = Blue",
  },
  {
    prompt: "Which of these means the color brown in Japanese?",
    optionA: "むらさき (Murasaki)",
    optionB: "ちゃいろ (Chairo)",
    optionC: "みどり (Midori)",
    optionD: "あお (Ao)",
    answer: "B",
    word: "ちゃいろ (Chairo) = Brown",
  },
];

export const JapaneseTransportationsQuestions = [
  {
    prompt: "Which of these is the word car in Japanese?",
    optionA: "じてんしゃ (Jitensha)",
    optionB: "ひこうき (Hikōki)",
    optionC: "くるま (Kuruma)",
    optionD: "ヘリコプター (Herikoputā)",
    answer: "C",
    word: "くるま (Kuruma) = Car",
  },
  {
    prompt: "Which of these is the word motorbike in Japanese?",
    optionA: "バイク (Baiku)",
    optionB: "ヘリコプター (Herikoputā)",
    optionC: "ボート (Boto)",
    optionD: "ひこうき (Hikōki)",
    answer: "A",
    word: "バイク (Baiku) = Motorbike",
  },
  {
    prompt: "Which of these is the word bicycle in Japanese?",
    optionA: "バイク (Baiku)",
    optionB: "バス (Basu)",
    optionC: "ヨット (Yotto)",
    optionD: "じてんしゃ (Jitensha)",
    answer: "D",
    word: "じてんしゃ (Jitensha) = Bicycle",
  },
  {
    prompt: "Which of these is the word bus in Japanese?",
    optionA: "ヨット (Yotto)",
    optionB: "ヘリコプター (Herikoputā)",
    optionC: "ひこうき (Hikōki)",
    optionD: "バス (Basu)",
    answer: "D",
    word: "バス (Basu) = Bus",
  },
  {
    prompt: "Which of these is the word airplane in Japanese?",
    optionA: "ヘリコプター (Herikoputā)",
    optionB: "ひこうき (Hikōki)",
    optionC: "せんすいかん (Sensuikan)",
    optionD: "バス (Basu)",
    answer: "B",
    word: "ひこうき (Hikōki) = Plane",
  },
  {
    prompt: "Which of these is the word yacht in Japanese?",
    optionA: "でんしゃ (Densha)",
    optionB: "ヨット (Yotto)",
    optionC: "バイク (Baiku)",
    optionD: "せんすいかん (Sensuikan)",
    answer: "B",
    word: "ヨット (Yotto) = Yacht",
  },
  {
    prompt: "Which of these is the word helicopter in Japanese?",
    optionA: "ヘリコプター (Herikoputā)",
    optionB: "でんしゃ (Densha)",
    optionC: "しろ (Shiro)",
    optionD: "バイク (Baiku)",
    answer: "A",
    word: "ヘリコプター (Herikoputā) = Helicopter",
  },
  {
    prompt: "Which of these is the word train in Japanese?",
    optionA: "せんすいかん (Sensuikan)",
    optionB: "ボート (Boto)",
    optionC: "バイク (Baiku)",
    optionD: "でんしゃ (Densha)",
    answer: "D",
    word: "でんしゃ (Densha) = Train",
  },
  {
    prompt: "Which of these is the word boat in Japanese?",
    optionA: "ボート (Boto)",
    optionB: "くるま (Kuruma)",
    optionC: "でんしゃ (Densha)",
    optionD: "せんすいかん (Sensuikan)",
    answer: "A",
    word: "ボート (Boto) = Boat",
  },
  {
    prompt: "Which of these is the word submarine in Japanese?",
    optionA: "ボート (Boto)",
    optionB: "せんすいかん (Sensuikan)",
    optionC: "くるま (Kuruma)",
    optionD: "ヨット (Yotto)",
    answer: "A",
    word: "	せんすいかん (Sensuikan) = Submarine",
  },
];

export const JapaneseHumanBodyQuestions = [
  {
    prompt: "Which of these is these mean ears in Japanese?",
    optionA: "て (Te)",
    optionB: "みみ (Mimi)",
    optionC: "ゆび (Yubi)",
    optionD: "はな (Hana)",
    answer: "B",
    word: "みみ (Mimi) = Ears",
  },
  {
    prompt: "Which of these is these means nose in Japanese?",
    optionA: "はな (Hana)",
    optionB: "からだ (Karada)",
    optionC: "ひざ (Hiza)",
    optionD: "て (Te)",
    answer: "A",
    word: "はな (Hana) = Nose",
  },
  {
    prompt: "Which of these is these mean fingers in Japanese?",
    optionA: "ゆび (Yubi)",
    optionB: "みみ (Mimi)",
    optionC: "からだ (Karada)",
    optionD: "ほね (Hone)",
    answer: "A",
    word: "ゆび (Yubi) = Fingers",
  },
  {
    prompt: "Which of these is these mean knees in Japanese?",
    optionA: "て (Te)",
    optionB: "はな (Hana)",
    optionC: "ゆび (Yubi)",
    optionD: "ひざ (Hiza)",
    answer: "D",
    word: "ひざ (Hiza) = Knees",
  },
  {
    prompt: "Which of these is these mean elbows in Japanese?",
    optionA: "みみ (Mimi)",
    optionB: "ほね (Hone)",
    optionC: "ひじ (Hiji)",
    optionD: "て (Te)",
    answer: "C",
    word: "ひじ (Hiji) = Elbows",
  },
  {
    prompt: "Which of these is these means face in Japanese?",
    optionA: "はな (Hana)",
    optionB: "かお (Kao)",
    optionC: "ゆび (Yubi)",
    optionD: "ほね (Hone)",
    answer: "B",
    word: "かお (Kao) = Face",
  },
  {
    prompt: "Which of these is these means body in Japanese?",
    optionA: "て (Te)",
    optionB: "ほね (Hone)",
    optionC: "みみ (Mimi)",
    optionD: "からだ (Karada)",
    answer: "D",
    word: "からだ (Karada) = Body",
  },
  {
    prompt: "Which of these is these mean hands in Japanese?",
    optionA: "ゆび (Yubi)",
    optionB: "ひざ (Hiza)",
    optionC: "はな (Hana)",
    optionD: "て (Te)",
    answer: "D",
    word: "て (Te) = Hands",
  },
  {
    prompt: "Which of these is these means bone in Japanese?",
    optionA: "ほね (Hone)",
    optionB: "からだ (Karada)",
    optionC: "はな (Hana)",
    optionD: "みみ (Mimi)",
    answer: "A",
    word: "ほね (Hone) = Bone",
  },
];

export const JapaneseFruitsQuestions = [
  {
    prompt: "Which of these is these means the word apple in Japanese?",
    optionA: "メロン (Meron)",
    optionB: "ぶどう (Budou)",
    optionC: "りんご (Ringo)",
    optionD: "すいか (Suika)",
    answer: "C",
    word: "りんご (Ringo) = Apple",
  },
  {
    prompt: "Which of these is these means the word orange in Japanese?",
    optionA: "オレンジ (Orenji)",
    optionB: "ココナッツ (Kokonattsu)",
    optionC: "パイナップル (Painappuru)",
    optionD: "ぶどう (Budou)",
    answer: "A",
    word: "オレンジ (Orenji) = Orange",
  },
  {
    prompt: "Which of these is these means the word mango in Japanese?",
    optionA: "マンゴー (Mango)",
    optionB: "りんご (Ringo)",
    optionC: "すいか (Suika)",
    optionD: "メロン (Meron)",
    answer: "A",
    word: "マンゴー (Mango) = Mango",
  },
  {
    prompt: "Which of these is these means the word strawberry in Japanese?",
    optionA: "オレンジ (Orenji)",
    optionB: "いちご (Ichigo)",
    optionC: "ココナッツ (Kokonattsu)",
    optionD: "ぶどう (Budou)",
    answer: "B",
    word: "いちご (Ichigo) = Strawberry",
  },
  {
    prompt: "Which of these is these means the word banana in Japanese?",
    optionA: "りんご (Ringo)",
    optionB: "メロン (Meron)",
    optionC: "マンゴー (Mango)",
    optionD: "バナナ (Banana)",
    answer: "D",
    word: "バナナ (Banana) = Banana",
  },
  {
    prompt: "Which of these is these means the word lemon in Japanese?",
    optionA: "ぶどう (Budou)",
    optionB: "オレンジ (Orenji)",
    optionC: "レモン (Remon)",
    optionD: "ココナッツ (Kokonattsu)",
    answer: "C",
    word: "レモン (Remon) = Lemon",
  },
  {
    prompt: "Which of these is these means the word watermelon in Japanese?",
    optionA: "すいか (Suika)",
    optionB: "マンゴー (Mango)",
    optionC: "りんご (Ringo)",
    optionD: "メロン (Meron)",
    answer: "A",
    word: "すいか (Suika) = Watermelon",
  },
  {
    prompt: "Which of these is these means the word durian in Japanese?",
    optionA: "ココナッツ (Kokonattsu)",
    optionB: "ぶどう (Budou)",
    optionC: "ドリアン (Dorian)",
    optionD: "オレンジ (Orenji)",
    answer: "C",
    word: "ドリアン (Dorian) = Durian",
  },
  {
    prompt: "Which of these is these means the word pineapple in Japanese?",
    optionA: "パイナップル (Painappuru)",
    optionB: "りんご (Ringo)",
    optionC: "メロン (Meron)",
    optionD: "マンゴー (Mango)",
    answer: "A",
    word: "パイナップル (Painappuru) = Pineapple",
  },
  {
    prompt: "Which of these is these means the word grape in Japanese?",
    optionA: "ぶどう (Budou)",
    optionB: "ココナッツ (Kokonattsu)",
    optionC: "いちご (Ichigo)",
    optionD: "オレンジ (Orenji)",
    answer: "A",
    word: "ぶどう (Budou) = Grape",
  },
  {
    prompt: "Which of these is these means the word melon in Japanese?",
    optionA: "いちご (Ichigo)",
    optionB: "メロン (Meron)",
    optionC: "りんご (Ringo)",
    optionD: "バナナ (Banana)",
    answer: "B",
    word: "メロン (Meron) = Melon",
  },
  {
    prompt: "Which of these is these means the word coconut in Japanese?",
    optionA: "オレンジ (Orenji)",
    optionB: "レモン (Remon)",
    optionC: "ココナッツ (Kokonattsu)",
    optionD: "いちご (Ichigo)",
    answer: "C",
    word: "ココナッツ (Kokonattsu) = Coconut",
  },
];

export const GermanAnimalsQuestions = [
  {
    prompt: "Which of these means cat in German?",
    optionA: "Kuh",
    optionB: "Hund",
    optionC: "Katze",
    optionD: "Fische",
    answer: "C",
    word: "Katze = Cat",
  },
  {
    prompt: "Which of these means fish in German?",
    optionA: "Fische",
    optionB: "Katze",
    optionC: "Affe",
    optionD: "Hirsch",
    answer: "A",
    word: "Fische = Fish",
  },
  {
    prompt: "Which of these means rabbit in German?",
    optionA: "Hund",
    optionB: "Ente",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "D",
    word: "Hase = Rabbit",
  },
  {
    prompt: "Which of these means dog in German?",
    optionA: "Vogel",
    optionB: "Kamel",
    optionC: "Fische",
    optionD: "Hund",
    answer: "D",
    word: "Hund = Dog",
  },
  {
    prompt: "Which of these means bird in German?",
    optionA: "Kamel",
    optionB: "Ziege",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "C",
    word: "Vogel = Bird",
  },
  {
    prompt: "Which of these means pig in German?",
    optionA: "Katze",
    optionB: "Schwein",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "B",
    word: "Schwein = Pig",
  },
  {
    prompt: "Which of these means duck in German?",
    optionA: "Kamel",
    optionB: "Hund",
    optionC: "Ente",
    optionD: "Hähnchen",
    answer: "C",
    word: "Ente = Duck",
  },
  {
    prompt: "Which of these means chicken in German?",
    optionA: "Hähnchen",
    optionB: "Schwein",
    optionC: "Hirsch",
    optionD: "Hase",
    answer: "A",
    word: "Hähnchen = Chicken",
  },
  {
    prompt: "Which of these means cow in German?",
    optionA: "Katze",
    optionB: "Kuh",
    optionC: "Ente",
    optionD: "Ziege",
    answer: "B",
    word: "Kuh = Cow",
  },
  {
    prompt: "Which of these means fox in German?",
    optionA: "Hähnchen",
    optionB: "Kamel",
    optionC: "Ente",
    optionD: "Fuchs",
    answer: "D",
    word: "Fuchs = Fox",
  },
  {
    prompt: "Which of these means deer in German?",
    optionA: "Hähnchen",
    optionB: "Hirsch",
    optionC: "Fuchs",
    optionD: "Vogel",
    answer: "B",
    word: "Hirsch = Deer",
  },
];

export const GermanOccupationsQuestions = [
  {
    prompt: "Which of these means waiter in German?",
    optionA: "Der Krankenpfleger",
    optionB: "Der Arzt",
    optionC: "Der Lehrer",
    optionD: "Der Kellner",
    answer: "D",
    word: "Der Kellner = Waiter",
  },
  {
    prompt: "Which of these means doctor in German?",
    optionA: "Der Arzt",
    optionB: "Der Verkäufer",
    optionC: "Der Musiker",
    optionD: "Der Architekt",
    answer: "A",
    word: "Der Arzt = Doctor",
  },
  {
    prompt: "Which of these means architect in German?",
    optionA: "Der Architekt",
    optionB: "Der Lehrer",
    optionC: "Der Krankenpfleger",
    optionD: "Der Friseur",
    answer: "A",
    word: "Der Architekt = Architech",
  },
  {
    prompt: "Which of these means author in German?",
    optionA: "Der Kellner",
    optionB: "Der Friseur",
    optionC: "Der Autor",
    optionD: "Der Verkäufer",
    answer: "C",
    word: "Der Autor = Author",
  },
  {
    prompt: "Which of these means musician in German?",
    optionA: "Der Musiker",
    optionB: "der Krankenpfleger",
    optionC: "Der Architekt",
    optionD: "Der Arzt",
    answer: "A",
    word: "Der Musiker = Musician",
  },
  {
    prompt: "Which of these means teacher in German?",
    optionA: "Der Kellner",
    optionB: "Der Architekt",
    optionC: "Der Lehrer",
    optionD: "Der Friseur",
    answer: "C",
    word: "Der Lehrer = Teacher",
  },
  {
    prompt: "Which of these means hairdresser in German?",
    optionA: "Der Architekt",
    optionB: "Der Friseur",
    optionC: "Der Lehrer",
    optionD: "Der Verkäufer",
    answer: "B",
    word: "Der Friseur = Hairdresser",
  },
  {
    prompt: "Which of these means nurse in German?",
    optionA: "Der Krankenpfleger",
    optionB: "Der Musiker",
    optionC: "Der Verkäufer",
    optionD: "Der Kellner",
    answer: "A",
    word: "Der Krankenpfleger = Nurse",
  },
  {
    prompt: "Which of these means sales assistant in German?",
    optionA: "Der Arzt",
    optionB: "Der Verkäufer",
    optionC: "Der Krankenpfleger",
    optionD: "Der Lehrer",
    answer: "B",
    word: "Der Verkäufer = Sales assistant",
  },
  {
    prompt: "Which of these means translator in German?",
    optionA: "Der Verkäufer",
    optionB: "Der Lehrer",
    optionC: "Der Übersetzer ",
    optionD: "Der Krankenpfleger",
    answer: "C",
    word: "Der Übersetzer  = Translator",
  },
];

export const GermanGreetingsQuestions = [
  {
    prompt: "How do you say good morning in German?",
    optionA: "Guten tag",
    optionB: "Guten morgen",
    optionC: "Gute nacht",
    optionD: "Guten abend",
    answer: "B",
    word: "Guten morgen = Good morning",
  },
  {
    prompt: "How do you say bye in German?",
    optionA: "Guten morgen",
    optionB: "Hallo",
    optionC: "Tschüss",
    optionD: "Gute nacht",
    answer: "C",
    word: "Tschüss = Bye",
  },
  {
    prompt: "How do you say good afternoon in German?",
    optionA: "Guten abend",
    optionB: "Tschüss",
    optionC: "Guten tag",
    optionD: "Guten morgen",
    answer: "C",
    word: "Guten tag = Good afternoon",
  },
  {
    prompt: "How do you say good night in German?",
    optionA: "Hallo",
    optionB: "Tschüss",
    optionC: "Guten abend",
    optionD: "Gute nacht",
    answer: "D",
    word: "Gute nacht = Good night",
  },
  {
    prompt: "How do you say good evening in German?",
    optionA: "Guten abend",
    optionB: "Guten morgen",
    optionC: "Guten tag",
    optionD: "Hallo",
    answer: "A",
    word: "Guten abend = Good evening",
  },
  {
    prompt: "How do you say hello in German?",
    optionA: "Guten tag",
    optionB: "Hallo",
    optionC: "Guten abend",
    optionD: "Tschüss",
    answer: "B",
    word: "Hallo = Hello",
  },
];

export const GermanVegetablesQuestions = [
  {
    prompt: "What is carrot in German?",
    optionA: "Ingwerwurzel",
    optionB: "Karotte",
    optionC: "Paprika",
    optionD: "Gurke",
    answer: "B",
    word: "Karotte = Carrot",
  },
  {
    prompt: "What is potato in German?",
    optionA: "Gurke",
    optionB: "Brokkoli",
    optionC: "Kartoffel",
    optionD: "Paprika",
    answer: "C",
    word: "Kartoffel = Potato",
  },
  {
    prompt: "What is cucumber in German?",
    optionA: "Mais",
    optionB: "Knoblauch",
    optionC: "Ingwerwurzel",
    optionD: "Gurke",
    answer: "D",
    word: "Gurke = Cucumber",
  },
  {
    prompt: "What is eggplant in German?",
    optionA: "Aubergine",
    optionB: "Paprika",
    optionC: "Kartoffel",
    optionD: "Mais",
    answer: "A",
    word: "Aubergine = Eggplant",
  },
  {
    prompt: "What is cnion in German?",
    optionA: "Zwiebel",
    optionB: "Ingwerwurzel",
    optionC: "Knoblauch",
    optionD: "Gurke",
    answer: "A",
    word: "Zwiebel = Onion",
  },
  {
    prompt: "What is corn in German?",
    optionA: "Aubergine",
    optionB: "Paprika",
    optionC: "Kartoffel",
    optionD: "Mais",
    answer: "D",
    word: "Mais = Corn",
  },
  {
    prompt: "What is garlic in German?",
    optionA: "Kartoffel",
    optionB: "Brokkoli",
    optionC: "Ingwerwurzel",
    optionD: "Knoblauch",
    answer: "D",
    word: "Knoblauch = Garlic",
  },
  {
    prompt: "What is pumpkin in German?",
    optionA: "Brokkoli",
    optionB: "Gurke",
    optionC: "Kürbis",
    optionD: "Paprika",
    answer: "C",
    word: "Kürbis = Pumpkin",
  },
  {
    prompt: "What is leek in German?",
    optionA: "Lauch",
    optionB: "Paprika",
    optionC: "Ingwerwurzel",
    optionD: "Kartoffel",
    answer: "A",
    word: "Lauch = Leek",
  },
  {
    prompt: "What is broccoli in German?",
    optionA: "Aubergine",
    optionB: "Brokkoli",
    optionC: "Mais",
    optionD: "Gurke",
    answer: "B",
    word: "Brokkoli = Broccoli",
  },
  {
    prompt: "What is pepper in German?",
    optionA: "Ingwerwurzel",
    optionB: "Mais",
    optionC: "Paprika",
    optionD: "Kartoffel",
    answer: "C",
    word: "Paprika = Pepper",
  },
  {
    prompt: "What is ginger root in German?",
    optionA: "Gurke",
    optionB: "Paprika",
    optionC: "Ingwerwurzel",
    optionD: "Aubergine",
    answer: "C",
    word: "Ingwerwurzel = Ginger root",
  },
];
