export const JapaneseColorQuestions = [
  {
    prompt: "Which of these means the color green in Japanese?",
    optionA: "しろ (Shiro)",
    optionB: "みどり (Midori)",
    optionC: "くろ (Kuro)",
    optionD: "あか (Aka)",
    answer: "B",
    word: "みどり (Midori) = Green",
  },
  {
    prompt: "Which of these means the color yellow in Japanese?",
    optionA: "きいろ (Kiiro)",
    optionB: "くろ (Kuro)",
    optionC: "むらさき (Murasaki)",
    optionD: "みどり (Midori)",
    answer: "A",
    word: "きいろ (Kiiro) = Yellow",
  },
  {
    prompt: "Which of these means the color black in Japanese?",
    optionA: "くろ (Kuro)",
    optionB: "むらさき (Murasaki)",
    optionC: "しろ (Shiro)",
    optionD: "あお (Ao)",
    answer: "A",
    word: "くろ (Kuro) = Black",
  },
  {
    prompt: "Which of these means the color red in Japanese?",
    optionA: "あお (Ao)",
    optionB: "むらさき (Murasaki)",
    optionC: "ちゃいろ (Chairo)",
    optionD: "あか (Aka)",
    answer: "D",
    word: "あか (Aka) = Red",
  },
  {
    prompt: "Which of these means the color white in Japanese?",
    optionA: "ちゃいろ (Chairo)",
    optionB: "きいろ (Kiiro)",
    optionC: "しろ (Shiro)",
    optionD: "みどり (Midori)",
    answer: "C",
    word: "しろ (Shiro) = White",
  },
  {
    prompt: "Which of these means the color purple in Japanese?",
    optionA: "あか (Aka)",
    optionB: "くろ (Kuro)",
    optionC: "ちゃいろ (Chairo)",
    optionD: "むらさき (Murasaki)",
    answer: "D",
    word: "むらさき (Murasaki) = Purple",
  },
  {
    prompt: "Which of these means the color blue in Japanese?",
    optionA: "あお (Ao)",
    optionB: "きいろ (Kiiro)",
    optionC: "しろ (Shiro)",
    optionD: "くろ (Kuro)",
    answer: "A",
    word: "あお (Ao) = Blue",
  },
  {
    prompt: "Which of these means the color brown in Japanese?",
    optionA: "むらさき (Murasaki)",
    optionB: "ちゃいろ (Chairo)",
    optionC: "みどり (Midori)",
    optionD: "あお (Ao)",
    answer: "B",
    word: "ちゃいろ (Chairo) = Brown",
  },
];

export const JapaneseTransportationsQuestions = [
  {
    prompt: "Which of these is the word car in Japanese?",
    optionA: "じてんしゃ (Jitensha)",
    optionB: "ひこうき (Hikōki)",
    optionC: "くるま (Kuruma)",
    optionD: "ヘリコプター (Herikoputā)",
    answer: "C",
    word: "くるま (Kuruma) = Car",
  },
  {
    prompt: "Which of these is the word motorbike in Japanese?",
    optionA: "バイク (Baiku)",
    optionB: "ヘリコプター (Herikoputā)",
    optionC: "ボート (Boto)",
    optionD: "ひこうき (Hikōki)",
    answer: "A",
    word: "バイク (Baiku) = Motorbike",
  },
  {
    prompt: "Which of these is the word bicycle in Japanese?",
    optionA: "バイク (Baiku)",
    optionB: "バス (Basu)",
    optionC: "ヨット (Yotto)",
    optionD: "じてんしゃ (Jitensha)",
    answer: "D",
    word: "じてんしゃ (Jitensha) = Bicycle",
  },
  {
    prompt: "Which of these is the word bus in Japanese?",
    optionA: "ヨット (Yotto)",
    optionB: "ヘリコプター (Herikoputā)",
    optionC: "ひこうき (Hikōki)",
    optionD: "バス (Basu)",
    answer: "D",
    word: "バス (Basu) = Bus",
  },
  {
    prompt: "Which of these is the word airplane in Japanese?",
    optionA: "ヘリコプター (Herikoputā)",
    optionB: "ひこうき (Hikōki)",
    optionC: "せんすいかん (Sensuikan)",
    optionD: "バス (Basu)",
    answer: "B",
    word: "ひこうき (Hikōki) = Plane",
  },
  {
    prompt: "Which of these is the word yacht in Japanese?",
    optionA: "でんしゃ (Densha)",
    optionB: "ヨット (Yotto)",
    optionC: "バイク (Baiku)",
    optionD: "せんすいかん (Sensuikan)",
    answer: "B",
    word: "ヨット (Yotto) = Yacht",
  },
  {
    prompt: "Which of these is the word helicopter in Japanese?",
    optionA: "ヘリコプター (Herikoputā)",
    optionB: "でんしゃ (Densha)",
    optionC: "しろ (Shiro)",
    optionD: "バイク (Baiku)",
    answer: "A",
    word: "ヘリコプター (Herikoputā) = Helicopter",
  },
  {
    prompt: "Which of these is the word train in Japanese?",
    optionA: "せんすいかん (Sensuikan)",
    optionB: "ボート (Boto)",
    optionC: "バイク (Baiku)",
    optionD: "でんしゃ (Densha)",
    answer: "D",
    word: "でんしゃ (Densha) = Train",
  },
  {
    prompt: "Which of these is the word boat in Japanese?",
    optionA: "ボート (Boto)",
    optionB: "くるま (Kuruma)",
    optionC: "でんしゃ (Densha)",
    optionD: "せんすいかん (Sensuikan)",
    answer: "A",
    word: "ボート (Boto) = Boat",
  },
  {
    prompt: "Which of these is the word submarine in Japanese?",
    optionA: "ボート (Boto)",
    optionB: "せんすいかん (Sensuikan)",
    optionC: "くるま (Kuruma)",
    optionD: "ヨット (Yotto)",
    answer: "A",
    word: "	せんすいかん (Sensuikan) = Submarine",
  },
];

export const JapaneseHumanBodyQuestions = [
  {
    prompt: "Which of these mean ears in Japanese?",
    optionA: "て (Te)",
    optionB: "みみ (Mimi)",
    optionC: "ゆび (Yubi)",
    optionD: "はな (Hana)",
    answer: "B",
    word: "みみ (Mimi) = Ears",
  },
  {
    prompt: "Which of these means nose in Japanese?",
    optionA: "はな (Hana)",
    optionB: "からだ (Karada)",
    optionC: "ひざ (Hiza)",
    optionD: "て (Te)",
    answer: "A",
    word: "はな (Hana) = Nose",
  },
  {
    prompt: "Which of these mean fingers in Japanese?",
    optionA: "ゆび (Yubi)",
    optionB: "みみ (Mimi)",
    optionC: "からだ (Karada)",
    optionD: "ほね (Hone)",
    answer: "A",
    word: "ゆび (Yubi) = Fingers",
  },
  {
    prompt: "Which of these mean knees in Japanese?",
    optionA: "て (Te)",
    optionB: "はな (Hana)",
    optionC: "ゆび (Yubi)",
    optionD: "ひざ (Hiza)",
    answer: "D",
    word: "ひざ (Hiza) = Knees",
  },
  {
    prompt: "Which of these mean elbows in Japanese?",
    optionA: "みみ (Mimi)",
    optionB: "ほね (Hone)",
    optionC: "ひじ (Hiji)",
    optionD: "て (Te)",
    answer: "C",
    word: "ひじ (Hiji) = Elbows",
  },
  {
    prompt: "Which of these means face in Japanese?",
    optionA: "はな (Hana)",
    optionB: "かお (Kao)",
    optionC: "ゆび (Yubi)",
    optionD: "ほね (Hone)",
    answer: "B",
    word: "かお (Kao) = Face",
  },
  {
    prompt: "Which of these means body in Japanese?",
    optionA: "て (Te)",
    optionB: "ほね (Hone)",
    optionC: "みみ (Mimi)",
    optionD: "からだ (Karada)",
    answer: "D",
    word: "からだ (Karada) = Body",
  },
  {
    prompt: "Which of these mean hands in Japanese?",
    optionA: "ゆび (Yubi)",
    optionB: "ひざ (Hiza)",
    optionC: "はな (Hana)",
    optionD: "て (Te)",
    answer: "D",
    word: "て (Te) = Hands",
  },
  {
    prompt: "Which of these means bone in Japanese?",
    optionA: "ほね (Hone)",
    optionB: "からだ (Karada)",
    optionC: "はな (Hana)",
    optionD: "みみ (Mimi)",
    answer: "A",
    word: "ほね (Hone) = Bone",
  },
];

export const JapaneseFruitsQuestions = [
  {
    prompt: "Which of these means the word apple in Japanese?",
    optionA: "メロン (Meron)",
    optionB: "ぶどう (Budou)",
    optionC: "りんご (Ringo)",
    optionD: "すいか (Suika)",
    answer: "C",
    word: "りんご (Ringo) = Apple",
  },
  {
    prompt: "Which of these means the word orange in Japanese?",
    optionA: "オレンジ (Orenji)",
    optionB: "ココナッツ (Kokonattsu)",
    optionC: "パイナップル (Painappuru)",
    optionD: "ぶどう (Budou)",
    answer: "A",
    word: "オレンジ (Orenji) = Orange",
  },
  {
    prompt: "Which of these means the word mango in Japanese?",
    optionA: "マンゴー (Mango)",
    optionB: "りんご (Ringo)",
    optionC: "すいか (Suika)",
    optionD: "メロン (Meron)",
    answer: "A",
    word: "マンゴー (Mango) = Mango",
  },
  {
    prompt: "Which of these means the word strawberry in Japanese?",
    optionA: "オレンジ (Orenji)",
    optionB: "いちご (Ichigo)",
    optionC: "ココナッツ (Kokonattsu)",
    optionD: "ぶどう (Budou)",
    answer: "B",
    word: "いちご (Ichigo) = Strawberry",
  },
  {
    prompt: "Which of these means the word banana in Japanese?",
    optionA: "りんご (Ringo)",
    optionB: "メロン (Meron)",
    optionC: "マンゴー (Mango)",
    optionD: "バナナ (Banana)",
    answer: "D",
    word: "バナナ (Banana) = Banana",
  },
  {
    prompt: "Which of these means the word lemon in Japanese?",
    optionA: "ぶどう (Budou)",
    optionB: "オレンジ (Orenji)",
    optionC: "レモン (Remon)",
    optionD: "ココナッツ (Kokonattsu)",
    answer: "C",
    word: "レモン (Remon) = Lemon",
  },
  {
    prompt: "Which of these is these means the word watermelon in Japanese?",
    optionA: "すいか (Suika)",
    optionB: "マンゴー (Mango)",
    optionC: "りんご (Ringo)",
    optionD: "メロン (Meron)",
    answer: "A",
    word: "すいか (Suika) = Watermelon",
  },
  {
    prompt: "Which of these means the word durian in Japanese?",
    optionA: "ココナッツ (Kokonattsu)",
    optionB: "ぶどう (Budou)",
    optionC: "ドリアン (Dorian)",
    optionD: "オレンジ (Orenji)",
    answer: "C",
    word: "ドリアン (Dorian) = Durian",
  },
  {
    prompt: "Which of these means the word pineapple in Japanese?",
    optionA: "パイナップル (Painappuru)",
    optionB: "りんご (Ringo)",
    optionC: "メロン (Meron)",
    optionD: "マンゴー (Mango)",
    answer: "A",
    word: "パイナップル (Painappuru) = Pineapple",
  },
  {
    prompt: "Which of these means the word grape in Japanese?",
    optionA: "ぶどう (Budou)",
    optionB: "ココナッツ (Kokonattsu)",
    optionC: "いちご (Ichigo)",
    optionD: "オレンジ (Orenji)",
    answer: "A",
    word: "ぶどう (Budou) = Grape",
  },
  {
    prompt: "Which of these means the word melon in Japanese?",
    optionA: "いちご (Ichigo)",
    optionB: "メロン (Meron)",
    optionC: "りんご (Ringo)",
    optionD: "バナナ (Banana)",
    answer: "B",
    word: "メロン (Meron) = Melon",
  },
  {
    prompt: "Which of these means the word coconut in Japanese?",
    optionA: "オレンジ (Orenji)",
    optionB: "レモン (Remon)",
    optionC: "ココナッツ (Kokonattsu)",
    optionD: "いちご (Ichigo)",
    answer: "C",
    word: "ココナッツ (Kokonattsu) = Coconut",
  },
];

export const JapaneseStationeryQuestions = [
  {
    prompt: "Which of these means the word pencil in Japanese?",
    optionA: "チョーク (Cho-ku)",
    optionB: "かみ (Kami)",
    optionC: "マーカー (Ma-ka)",
    optionD: "えんぴつ (Enpitsu)",
    answer: "D",
    word: "えんぴつ (Enpitsu) = Pencil",
  },
  {
    prompt: "Which of these means the word pen in Japanese?",
    optionA: "ペン (Pen)",
    optionB: "マーカー (Ma-ka)",
    optionC: "チョーク (Cho-ku)",
    optionD: "いんかん (Inkan)",
    answer: "A",
    word: "ペン (Pen) = Pen",
  },
  {
    prompt: "Which of these means the word eraser in Japanese?",
    optionA: "けしゴム (Keshigomu)",
    optionB: "えんぴつ (Enpitsu)",
    optionC: "かみ (Kami)",
    optionD: "マーカー (Ma-ka)",
    answer: "A",
    word: "けしゴム (Keshigomu) = Eraser",
  },
  {
    prompt: "Which of these means the word paper in Japanese?",
    optionA: "いんかん (Inkan)",
    optionB: "チョーク (Cho-ku)",
    optionC: "かみ (Kami)",
    optionD: "ペン (Pen)",
    answer: "C",
    word: "かみ (Kami) = Paper",
  },
  {
    prompt: "Which of these means the word book in Japanese?",
    optionA: "けしゴム (Keshigomu)",
    optionB: "マーカー (Ma-ka)",
    optionC: "えんぴつ (Enpitsu)",
    optionD: "ほん (Hon)",
    answer: "D",
    word: "ほん (Hon) = Book",
  },
  {
    prompt: "Which of these means the word ruler in Japanese?",
    optionA: "いんかん (Inkan)",
    optionB: "ペン (Pen)",
    optionC: "チョーク (Cho-ku)",
    optionD: "じょうぎ (Jougi)",
    answer: "D",
    word: "じょうぎ (Jougi) = Ruler",
  },
  {
    prompt: "Which of these means the word stapler in Japanese?",
    optionA: "マーカー (Ma-ka)",
    optionB: "ホッチキス (Hocchikisu)",
    optionC: "えんぴつ (Enpitsu)",
    optionD: "けしゴム (Keshigomu)",
    answer: "B",
    word: "ホッチキス (Hocchikisu) = Stapler",
  },
  {
    prompt: "Which of these means the word crayon in Japanese?",
    optionA: "ペン (Pen)",
    optionB: "いんかん (Inkan)",
    optionC: "クレヨン (Kureyon)",
    optionD: "チョーク (Cho-ku)",
    answer: "C",
    word: "クレヨン (Kureyon) = Crayon",
  },
  {
    prompt: "Which of these means the word glue in Japanese?",
    optionA: "のり (Nori)",
    optionB: "えんぴつ (Enpitsu)",
    optionC: "マーカー (Ma-ka)",
    optionD: "ペン (Pen)",
    answer: "A",
    word: "のり (Nori) = Glue",
  },
  {
    prompt: "Which of these means the word chalk in Japanese?",
    optionA: "チョーク (Cho-ku)",
    optionB: "かみ (Kami)",
    optionC: "けしゴム (Keshigomu)",
    optionD: "いんかん (Inkan)",
    answer: "A",
    word: "チョーク (Cho-ku) = Chalk",
  },
  {
    prompt: "Which of these means the word marker in Japanese?",
    optionA: "かみ (Kami)",
    optionB: "マーカー (Ma-ka)",
    optionC: "ペン (Pen)",
    optionD: "えんぴつ (Enpitsu)",
    answer: "B",
    word: "マーカー (Ma-ka) = Marker",
  },
  {
    prompt: "Which of these means the word stamp in Japanese?",
    optionA: "マーカー (Ma-ka)",
    optionB: "けしゴム (Keshigomu)",
    optionC: "チョーク (Cho-ku)",
    optionD: "いんかん (Inkan)",
    answer: "D",
    word: "いんかん (Inkan) = Stamp",
  },
];

export const JapaneseAnimalsQuestions = [
  {
    prompt: "Which of these means cat in Japanese?",
    optionA: "ねこ (Neko)",
    optionB: "シカ	(Shika)",
    optionC: "ブタ	(Buta)",
    optionD: "いぬ	(Inu)",
    answer: "A",
    word: "ねこ (Neko) = Cat",
  },
  {
    prompt: "Which of these means fish in Japanese?",
    optionA: "さかな	(Sakana)",
    optionB: "キツネ	(Kitsune)",
    optionC: "ウサギ	(Usagi)",
    optionD: "ニワトリ	(Niwatori)",
    answer: "A",
    word: "さかな	(Sakana) = Fish",
  },
  {
    prompt: "Which of these means rabbit in Japanese?",
    optionA: "シカ	(Shika)",
    optionB: "ねこ (Neko)",
    optionC: "ブタ	(Buta)",
    optionD: "ウサギ	(Usagi)",
    answer: "D",
    word: "ウサギ	(Usagi) = Rabbit",
  },
  {
    prompt: "Which of these means dog in Japanese?",
    optionA: "さかな	(Sakana)",
    optionB: "ニワトリ	(Niwatori)",
    optionC: "キツネ	(Kitsune)",
    optionD: "いぬ	(Inu)",
    answer: "D",
    word: "いぬ	(Inu) = Dog",
  },
  {
    prompt: "Which of these means bird in Japanese?",
    optionA: "ウシ	(Ushi)",
    optionB: "シカ	(Shika)",
    optionC: "とり (Tori)",
    optionD: "ねこ (Neko)",
    answer: "C",
    word: "とり (Tori) = Bird",
  },
  {
    prompt: "Which of these means pig in Japanese?",
    optionA: "いぬ	(Inu)",
    optionB: "ブタ	(Buta)",
    optionC: "さかな	(Sakana)",
    optionD: "キツネ	(Kitsune)",
    answer: "B",
    word: "ブタ	(Buta) = Pig",
  },
  {
    prompt: "Which of these means domestic duck in Japanese?",
    optionA: "ねこ (Neko)",
    optionB: "ウシ	(Ushi)",
    optionC: "アヒル	(Ahiru)",
    optionD: "シカ	(Shika)",
    answer: "C",
    word: "アヒル	(Ahiru) = Domestic duck",
  },
  {
    prompt: "Which of these means chicken in Japanese?",
    optionA: "ニワトリ	(Niwatori)",
    optionB: "さかな	(Sakana)",
    optionC: "ウサギ	(Usagi)",
    optionD: "キツネ	(Kitsune)",
    answer: "A",
    word: "ニワトリ	(Niwatori) = Chicken",
  },
  {
    prompt: "Which of these means cow in Japanese?",
    optionA: "シカ	(Shika)",
    optionB: "ウシ	(Ushi)",
    optionC: "ニワトリ	(Niwatori)",
    optionD: "ねこ (Neko)",
    answer: "B",
    word: "ウシ	(Ushi) = Cow",
  },
  {
    prompt: "Which of these means fox in Japanese?",
    optionA: "さかな	(Sakana)",
    optionB: "いぬ	(Inu)",
    optionC: "ブタ	(Buta)",
    optionD: "キツネ	(Kitsune)",
    answer: "D",
    word: "キツネ	(Kitsune) = Fox",
  },
  {
    prompt: "Which of these means deer in Japanese?",
    optionA: "ねこ (Neko)",
    optionB: "シカ	(Shika)",
    optionC: "ブタ	(Buta)",
    optionD: "ウシ	(Ushi)",
    answer: "B",
    word: "シカ	(Shika) = Deer",
  },
];

export const JapaneseGreetingsQuestions = [
  {
    prompt: "How do you say good morning in Japanese?",
    optionA: "ではまた (Dewa mata)",
    optionB: "おはようございます (Ohayou gozaimasu)",
    optionC: "こんばんは (Konbanwa)",
    optionD: "さようなら (Sayounara)",
    answer: "B",
    word: "おはようございます (Ohayou gozaimasu) = Good morning",
  },
  {
    prompt: "How do you say good bye in Japanese?",
    optionA: "おはようございます (Ohayou gozaimasu)",
    optionB: "おやすみなさい (O yasumi nasai)",
    optionC: "さようなら (Sayounara)",
    optionD: "こんにちは (Konnichiwa)",
    answer: "C",
    word: "さようなら (Sayounara) = Good Bye",
  },
  {
    prompt: "How do you say good afternoon in Japanese?",
    optionA: "おはようございます (Ohayou gozaimasu)",
    optionB: "おやすみなさい (O yasumi nasai)",
    optionC: "こんにちは (Konnichiwa)",
    optionD: "ではまた (Dewa mata)",
    answer: "C",
    word: "こんにちは (Konnichiwa) = Good afternoon",
  },
  {
    prompt: "How do you say good night in Japanese?",
    optionA: "こんにちは (Konnichiwa)",
    optionB: "さようなら (Sayounara)",
    optionC: "こんばんは (Konbanwa)",
    optionD: "おやすみなさい (O yasumi nasai)",
    answer: "D",
    word: "おやすみなさい (O yasumi nasai) = Good night",
  },
  {
    prompt: "How do you say good evening in Japanese?",
    optionA: "こんばんは (Konbanwa)",
    optionB: "おはようございます (Ohayou gozaimasu)",
    optionC: "こんにちは (Konnichiwa)",
    optionD: "ではまた (Dewa mata)",
    answer: "A",
    word: "こんばんは (Konbanwa) = Good evening",
  },
  {
    prompt: "How do you say see you in Japanese?",
    optionA: "こんにちは (Konnichiwa)",
    optionB: "ではまた (Dewa mata)",
    optionC: "こんばんは (Konbanwa)",
    optionD: "さようなら (Sayounara)",
    answer: "B",
    word: "ではまた (Dewa mata) = See you",
  },
];

export const JapaneseNumbersQuestions = [
  {
    prompt: "What is one (1) in Japanese?",
    optionA: "ご (Go)",
    optionB: "はち	(Hachi)",
    optionC: "いち (Ichi)",
    optionD: "じゅう	(Juu)",
    answer: "C",
    word: "いち (Ichi) = One (1)",
  },
  {
    prompt: "What is two (2) in Japanese?",
    optionA: "はち	(Hachi)",
    optionB: "に (Ni)",
    optionC: "ろく	(Roku)",
    optionD: "しち/なな	(Shichi/Nana)",
    answer: "B",
    word: "に (Ni) = Two (2)",
  },
  {
    prompt: "What is three (3) in Japanese?",
    optionA: "さん	(San)",
    optionB: "し/よん	(Shi/Yon)",
    optionC: "じゅう	(Juu)",
    optionD: "いち (Ichi)",
    answer: "A",
    word: "さん	(San) = Three (3)",
  },
  {
    prompt: "What is four (4) in Japanese?",
    optionA: "に (Ni)",
    optionB: "きゅう/く	(Kyu/ku)",
    optionC: "はち	(Hachi)",
    optionD: "し/よん	(Shi/Yon)",
    answer: "D",
    word: "し/よん	(Shi/Yon) = Four (4)",
  },
  {
    prompt: "What is five (5) in Japanese?",
    optionA: "じゅう	(Juu)",
    optionB: "はち	(Hachi)",
    optionC: "さん	(San)",
    optionD: "ご (Go)",
    answer: "D",
    word: "ご (Go) = Five (5)",
  },
  {
    prompt: "What is six (6) in Japanese?",
    optionA: "さん	(San)",
    optionB: "いち (Ichi)",
    optionC: "ろく	(Roku)",
    optionD: "に (Ni)",
    answer: "C",
    word: "ろく	(Roku) = Six (6)",
  },
  {
    prompt: "What is seven (7) in Japanese?",
    optionA: "いち (Ichi)",
    optionB: "しち/なな	(Shichi/Nana)",
    optionC: "ろく	(Roku)",
    optionD: "きゅう/く	(Kyu/ku)",
    answer: "B",
    word: "しち/なな	(Shichi/Nana) = Seven (7)",
  },
  {
    prompt: "What is eight (8) in Japanese?",
    optionA: "はち	(Hachi)",
    optionB: "に (Ni)",
    optionC: "さん	(San)",
    optionD: "じゅう	(Juu)",
    answer: "A",
    word: "はち	(Hachi) = Eight (8)",
  },
  {
    prompt: "What is nine (9) in Japanese?",
    optionA: "きゅう/く	(Kyu/ku)",
    optionB: "はち	(Hachi)",
    optionC: "し/よん	(Shi/Yon)",
    optionD: "しち/なな	(Shichi/Nana)",
    answer: "A",
    word: "きゅう/く	(Kyu/ku) = Nine (9)",
  },
  {
    prompt: "What is ten (10) in Japanese?",
    optionA: "に (Ni)",
    optionB: "ご (Go)",
    optionC: "じゅう (Juu)",
    optionD: "きゅう/く	(Kyu/ku)",
    answer: "C",
    word: "じゅう	(Juu) = Ten (10)",
  },
];

export const JapaneseOccupationsQuestions = [
  {
    prompt: "Which of these means farmer in Japanese?",
    optionA: "たんてい	(Tantei)",
    optionB: "いしゃ	(Isha)",
    optionC: "かんごし	(Kango shi)",
    optionD: "のうみん	(Noumin)",
    answer: "D",
    word: "のうみん	(Noumin) = Farmer",
  },
  {
    prompt: "Which of these means doctor in Japanese?",
    optionA: "いしゃ	(Isha)",
    optionB: "けんちくか	(Kenchiku ka)",
    optionC: "けいびいん	(Keibi in)",
    optionD: "かんごし	(Kango shi)",
    answer: "A",
    word: "いしゃ	(Isha) = Doctor",
  },
  {
    prompt: "Which of these means architect in Japanese?",
    optionA: "けんちくか	(Kenchiku ka)",
    optionB: "たんてい	(Tantei)",
    optionC: "せんせい	(Sensei)",
    optionD: "のうみん	(Noumin)",
    answer: "A",
    word: "けんちくか	(Kenchiku ka) = Architect",
  },
  {
    prompt: "Which of these means author in Japanese?",
    optionA: "かんごし	(Kango shi)",
    optionB: "びようし	(Biyou shi)",
    optionC: "さっか	(Sakka)",
    optionD: "せんせい	(Sensei)",
    answer: "C",
    word: "さっか	(Sakka) = Author",
  },
  {
    prompt: "Which of these means performing musician in Japanese?",
    optionA: "えんそうか	(Ensou ka)",
    optionB: "のうみん	(Noumin)",
    optionC: "けんちくか	(Kenchiku ka)",
    optionD: "いしゃ	(Isha)",
    answer: "A",
    word: "えんそうか	(Ensou ka) = Musician",
  },
  {
    prompt: "Which of these means teacher in Japanese?",
    optionA: "さっか	(Sakka)",
    optionB: "たんてい	(Tantei)",
    optionC: "せんせい	(Sensei)",
    optionD: "けいびいん	(Keibi in)",
    answer: "C",
    word: "せんせい	(Sensei) = Teacher",
  },
  {
    prompt: "Which of these means hairdresser in Japanese?",
    optionA: "いしゃ	(Isha)",
    optionB: "びようし	(Biyou shi)",
    optionC: "のうみん	(Noumin)",
    optionD: "せんせい	(Sensei)",
    answer: "B",
    word: "びようし	(Biyou shi) = Hairdresser",
  },
  {
    prompt: "Which of these means nurse in Japanese?",
    optionA: "かんごし	(Kango shi)",
    optionB: "びようし	(Biyou shi)",
    optionC: "さっか	(Sakka)",
    optionD: "たんてい	(Tantei)",
    answer: "A",
    word: "かんごし	(Kango shi) = Nurse",
  },
  {
    prompt: "Which of these means security guard in Japanese?",
    optionA: "さっか	(Sakka)",
    optionB: "けいびいん	(Keibi in)",
    optionC: "かんごし	(Kango shi)",
    optionD: "のうみん	(Noumin)",
    answer: "B",
    word: "けいびいん	(Keibi in) = Security guard",
  },
  {
    prompt: "Which of these means detective in Japanese?",
    optionA: "いしゃ	(Isha)",
    optionB: "さっか	(Sakka)",
    optionC: "たんてい	(Tantei)",
    optionD: "けいびいん	(Keibi in)",
    answer: "C",
    word: "たんてい	(Tantei)  = Detective",
  },
];

export const JapaneseVegetableQuestions = [
  {
    prompt: "What is carrot in Japanese?",
    optionA: "トウモロコシ	(Toumorokoshi)",
    optionB: "にんじん	(Ninjin)",
    optionC: "たまねぎ	(Tamanegi)",
    optionD: "ジャガイモ	(Jagaimo)",
    answer: "B",
    word: "にんじん	(Ninjin) = Carrot",
  },
  {
    prompt: "What is potato in Japanese?",
    optionA: "しょうが	(Shouga)",
    optionB: "かぼちゃ	(Kabocha)",
    optionC: "ジャガイモ	(Jagaimo)",
    optionD: "ナス	(Nasu)",
    answer: "C",
    word: "ジャガイモ	(Jagaimo) = Potato",
  },
  {
    prompt: "What is cucumber in Japanese?",
    optionA: "トウモロコシ	(Toumorokoshi)",
    optionB: "にんじん	(Ninjin)",
    optionC: "かぼちゃ	(Kabocha)",
    optionD: "きゅうり	(Kyuuri)",
    answer: "D",
    word: "きゅうり	(Kyuuri) = Cucumber",
  },
  {
    prompt: "What is eggplant in Japanese?",
    optionA: "ナス	(Nasu)",
    optionB: "にんにく	(Ninniku)",
    optionC: "ジャガイモ	(Jagaimo)",
    optionD: "しょうが	(Shouga)",
    answer: "A",
    word: "ナス	(Nasu) = Eggplant",
  },
  {
    prompt: "What is onion in Japanese?",
    optionA: "たまねぎ	(Tamanegi)",
    optionB: "トウモロコシ	(Toumorokoshi)",
    optionC: "にんじん	(Ninjin)",
    optionD: "ナス	(Nasu)",
    answer: "A",
    word: "たまねぎ	(Tamanegi) = Onion",
  },
  {
    prompt: "What is corn in Japanese?",
    optionA: "かぼちゃ	(Kabocha)",
    optionB: "ブロッコリー	(Burokkori)",
    optionC: "しょうが	(Shouga)",
    optionD: "トウモロコシ	(Toumorokoshi)",
    answer: "D",
    word: "トウモロコシ	(Toumorokoshi) = Corn",
  },
  {
    prompt: "What is garlic in Japanese?",
    optionA: "にんじん	(Ninjin)",
    optionB: "たまねぎ	(Tamanegi)",
    optionC: "きゅうり	(Kyuuri)",
    optionD: "にんにく	(Ninniku)",
    answer: "D",
    word: "にんにく	(Ninniku) = Garlic",
  },
  {
    prompt: "What is pumpkin in Japanese?",
    optionA: "しょうが	(Shouga)",
    optionB: "にんにく	(Ninniku)",
    optionC: "かぼちゃ	(Kabocha)",
    optionD: "にんじん	(Ninjin)",
    answer: "C",
    word: "かぼちゃ	(Kabocha) = Pumpkin",
  },
  {
    prompt: "What is broccoli in Japanese?",
    optionA: "きゅうり	(Kyuuri)",
    optionB: "ブロッコリー	(Burokkori)",
    optionC: "かぼちゃ	(Kabocha)",
    optionD: "たまねぎ	(Tamanegi)",
    answer: "B",
    word: "ブロッコリー	(Burokkori) = Broccoli",
  },
  {
    prompt: "What is ginger in Japanese?",
    optionA: "ブロッコリー	(Burokkori)",
    optionB: "トウモロコシ	(Toumorokoshi)",
    optionC: "しょうが	(Shouga)",
    optionD: "にんじん	(Ninjin)",
    answer: "C",
    word: "しょうが	(Shouga) = Ginger",
  },
];

export const GermanAnimalsQuestions = [
  {
    prompt: "Which of these means cat in German?",
    optionA: "Kuh",
    optionB: "Hund",
    optionC: "Katze",
    optionD: "Fische",
    answer: "C",
    word: "Katze = Cat",
  },
  {
    prompt: "Which of these means fish in German?",
    optionA: "Fische",
    optionB: "Katze",
    optionC: "Affe",
    optionD: "Hirsch",
    answer: "A",
    word: "Fische = Fish",
  },
  {
    prompt: "Which of these means rabbit in German?",
    optionA: "Hund",
    optionB: "Ente",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "D",
    word: "Hase = Rabbit",
  },
  {
    prompt: "Which of these means dog in German?",
    optionA: "Vogel",
    optionB: "Kamel",
    optionC: "Fische",
    optionD: "Hund",
    answer: "D",
    word: "Hund = Dog",
  },
  {
    prompt: "Which of these means bird in German?",
    optionA: "Kamel",
    optionB: "Ziege",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "C",
    word: "Vogel = Bird",
  },
  {
    prompt: "Which of these means pig in German?",
    optionA: "Katze",
    optionB: "Schwein",
    optionC: "Vogel",
    optionD: "Hase",
    answer: "B",
    word: "Schwein = Pig",
  },
  {
    prompt: "Which of these means duck in German?",
    optionA: "Kamel",
    optionB: "Hund",
    optionC: "Ente",
    optionD: "Hähnchen",
    answer: "C",
    word: "Ente = Duck",
  },
  {
    prompt: "Which of these means chicken in German?",
    optionA: "Hähnchen",
    optionB: "Schwein",
    optionC: "Hirsch",
    optionD: "Hase",
    answer: "A",
    word: "Hähnchen = Chicken",
  },
  {
    prompt: "Which of these means cow in German?",
    optionA: "Katze",
    optionB: "Kuh",
    optionC: "Ente",
    optionD: "Ziege",
    answer: "B",
    word: "Kuh = Cow",
  },
  {
    prompt: "Which of these means fox in German?",
    optionA: "Hähnchen",
    optionB: "Kamel",
    optionC: "Ente",
    optionD: "Fuchs",
    answer: "D",
    word: "Fuchs = Fox",
  },
  {
    prompt: "Which of these means deer in German?",
    optionA: "Hähnchen",
    optionB: "Hirsch",
    optionC: "Fuchs",
    optionD: "Vogel",
    answer: "B",
    word: "Hirsch = Deer",
  },
];

export const GermanOccupationsQuestions = [
  {
    prompt: "Which of these means waiter in German?",
    optionA: "Der Krankenpfleger",
    optionB: "Der Arzt",
    optionC: "Der Lehrer",
    optionD: "Der Kellner",
    answer: "D",
    word: "Der Kellner = Waiter",
  },
  {
    prompt: "Which of these means doctor in German?",
    optionA: "Der Arzt",
    optionB: "Der Verkäufer",
    optionC: "Der Musiker",
    optionD: "Der Architekt",
    answer: "A",
    word: "Der Arzt = Doctor",
  },
  {
    prompt: "Which of these means architect in German?",
    optionA: "Der Architekt",
    optionB: "Der Lehrer",
    optionC: "Der Krankenpfleger",
    optionD: "Der Friseur",
    answer: "A",
    word: "Der Architekt = Architech",
  },
  {
    prompt: "Which of these means author in German?",
    optionA: "Der Kellner",
    optionB: "Der Friseur",
    optionC: "Der Autor",
    optionD: "Der Verkäufer",
    answer: "C",
    word: "Der Autor = Author",
  },
  {
    prompt: "Which of these means musician in German?",
    optionA: "Der Musiker",
    optionB: "der Krankenpfleger",
    optionC: "Der Architekt",
    optionD: "Der Arzt",
    answer: "A",
    word: "Der Musiker = Musician",
  },
  {
    prompt: "Which of these means teacher in German?",
    optionA: "Der Kellner",
    optionB: "Der Architekt",
    optionC: "Der Lehrer",
    optionD: "Der Friseur",
    answer: "C",
    word: "Der Lehrer = Teacher",
  },
  {
    prompt: "Which of these means hairdresser in German?",
    optionA: "Der Architekt",
    optionB: "Der Friseur",
    optionC: "Der Lehrer",
    optionD: "Der Verkäufer",
    answer: "B",
    word: "Der Friseur = Hairdresser",
  },
  {
    prompt: "Which of these means nurse in German?",
    optionA: "Der Krankenpfleger",
    optionB: "Der Musiker",
    optionC: "Der Verkäufer",
    optionD: "Der Kellner",
    answer: "A",
    word: "Der Krankenpfleger = Nurse",
  },
  {
    prompt: "Which of these means sales assistant in German?",
    optionA: "Der Arzt",
    optionB: "Der Verkäufer",
    optionC: "Der Krankenpfleger",
    optionD: "Der Lehrer",
    answer: "B",
    word: "Der Verkäufer = Sales assistant",
  },
  {
    prompt: "Which of these means translator in German?",
    optionA: "Der Verkäufer",
    optionB: "Der Lehrer",
    optionC: "Der Übersetzer ",
    optionD: "Der Krankenpfleger",
    answer: "C",
    word: "Der Übersetzer  = Translator",
  },
];

export const GermanGreetingsQuestions = [
  {
    prompt: "How do you say good morning in German?",
    optionA: "Guten tag",
    optionB: "Guten morgen",
    optionC: "Gute nacht",
    optionD: "Guten abend",
    answer: "B",
    word: "Guten morgen = Good morning",
  },
  {
    prompt: "How do you say bye in German?",
    optionA: "Guten morgen",
    optionB: "Hallo",
    optionC: "Tschüss",
    optionD: "Gute nacht",
    answer: "C",
    word: "Tschüss = Bye",
  },
  {
    prompt: "How do you say good afternoon in German?",
    optionA: "Guten abend",
    optionB: "Tschüss",
    optionC: "Guten tag",
    optionD: "Guten morgen",
    answer: "C",
    word: "Guten tag = Good afternoon",
  },
  {
    prompt: "How do you say good night in German?",
    optionA: "Hallo",
    optionB: "Tschüss",
    optionC: "Guten abend",
    optionD: "Gute nacht",
    answer: "D",
    word: "Gute nacht = Good night",
  },
  {
    prompt: "How do you say good evening in German?",
    optionA: "Guten abend",
    optionB: "Guten morgen",
    optionC: "Guten tag",
    optionD: "Hallo",
    answer: "A",
    word: "Guten abend = Good evening",
  },
  {
    prompt: "How do you say hello in German?",
    optionA: "Guten tag",
    optionB: "Hallo",
    optionC: "Guten abend",
    optionD: "Tschüss",
    answer: "B",
    word: "Hallo = Hello",
  },
];

export const GermanVegetablesQuestions = [
  {
    prompt: "What is carrot in German?",
    optionA: "Ingwerwurzel",
    optionB: "Karotte",
    optionC: "Paprika",
    optionD: "Gurke",
    answer: "B",
    word: "Karotte = Carrot",
  },
  {
    prompt: "What is potato in German?",
    optionA: "Gurke",
    optionB: "Brokkoli",
    optionC: "Kartoffel",
    optionD: "Paprika",
    answer: "C",
    word: "Kartoffel = Potato",
  },
  {
    prompt: "What is cucumber in German?",
    optionA: "Mais",
    optionB: "Knoblauch",
    optionC: "Ingwerwurzel",
    optionD: "Gurke",
    answer: "D",
    word: "Gurke = Cucumber",
  },
  {
    prompt: "What is eggplant in German?",
    optionA: "Aubergine",
    optionB: "Paprika",
    optionC: "Kartoffel",
    optionD: "Mais",
    answer: "A",
    word: "Aubergine = Eggplant",
  },
  {
    prompt: "What is cnion in German?",
    optionA: "Zwiebel",
    optionB: "Ingwerwurzel",
    optionC: "Knoblauch",
    optionD: "Gurke",
    answer: "A",
    word: "Zwiebel = Onion",
  },
  {
    prompt: "What is corn in German?",
    optionA: "Aubergine",
    optionB: "Paprika",
    optionC: "Kartoffel",
    optionD: "Mais",
    answer: "D",
    word: "Mais = Corn",
  },
  {
    prompt: "What is garlic in German?",
    optionA: "Kartoffel",
    optionB: "Brokkoli",
    optionC: "Ingwerwurzel",
    optionD: "Knoblauch",
    answer: "D",
    word: "Knoblauch = Garlic",
  },
  {
    prompt: "What is pumpkin in German?",
    optionA: "Brokkoli",
    optionB: "Gurke",
    optionC: "Kürbis",
    optionD: "Paprika",
    answer: "C",
    word: "Kürbis = Pumpkin",
  },
  {
    prompt: "What is leek in German?",
    optionA: "Lauch",
    optionB: "Paprika",
    optionC: "Ingwerwurzel",
    optionD: "Kartoffel",
    answer: "A",
    word: "Lauch = Leek",
  },
  {
    prompt: "What is broccoli in German?",
    optionA: "Aubergine",
    optionB: "Brokkoli",
    optionC: "Mais",
    optionD: "Gurke",
    answer: "B",
    word: "Brokkoli = Broccoli",
  },
  {
    prompt: "What is pepper in German?",
    optionA: "Ingwerwurzel",
    optionB: "Mais",
    optionC: "Paprika",
    optionD: "Kartoffel",
    answer: "C",
    word: "Paprika = Pepper",
  },
  {
    prompt: "What is ginger root in German?",
    optionA: "Gurke",
    optionB: "Paprika",
    optionC: "Ingwerwurzel",
    optionD: "Aubergine",
    answer: "C",
    word: "Ingwerwurzel = Ginger root",
  },
];

export const GermanNumbersQuestions = [
  {
    prompt: "What is one (1) in German?",
    optionA: "Neun",
    optionB: "Zehn",
    optionC: "Eins",
    optionD: "Zwei",
    answer: "C",
    word: "Eins = One (1)",
  },
  {
    prompt: "What is two (2) in German?",
    optionA: "Fünf",
    optionB: "Zwei",
    optionC: "Vier",
    optionD: "Acht",
    answer: "B",
    word: "Zwei = Two (2)",
  },
  {
    prompt: "What is three (3) in German?",
    optionA: "Drei",
    optionB: "Eins",
    optionC: "Neun",
    optionD: "Zehn",
    answer: "A",
    word: "Drei = Three (3)",
  },
  {
    prompt: "What is four (4) in German?",
    optionA: "Eins",
    optionB: "Sechs",
    optionC: "Zwei",
    optionD: "Vier",
    answer: "D",
    word: "Vier = Four (4)",
  },
  {
    prompt: "What is five (5) in German?",
    optionA: "Zehn",
    optionB: "Neun",
    optionC: "Acht",
    optionD: "Fünf",
    answer: "D",
    word: "Fünf = Five (5)",
  },
  {
    prompt: "What is six (6) in German?",
    optionA: "Sieben",
    optionB: "Fünf",
    optionC: "Sechs",
    optionD: "Eins",
    answer: "C",
    word: "Sechs = Six (6)",
  },
  {
    prompt: "What is seven (7) in German?",
    optionA: "Neun",
    optionB: "Sieben",
    optionC: "Zwei",
    optionD: "Zehn",
    answer: "B",
    word: "Sieben = Seven (7)",
  },
  {
    prompt: "What is eight (8) in German?",
    optionA: "Acht",
    optionB: "Eins",
    optionC: "Sechs",
    optionD: "Vier",
    answer: "A",
    word: "Acht = Eight (8)",
  },
  {
    prompt: "What is nine (9) in German?",
    optionA: "Neun",
    optionB: "Zehn",
    optionC: "Vier",
    optionD: "Acht",
    answer: "A",
    word: "Neun = Nine (9)",
  },
  {
    prompt: "What is ten (10) in German?",
    optionA: "Sieben",
    optionB: "Fünf",
    optionC: "Zehn",
    optionD: "Eins",
    answer: "C",
    word: "Zehn = Ten (10)",
  },
];

export const GermanColorQuestions = [
  {
    prompt: "Which of these means the color green in German?",
    optionA: "Gelb",
    optionB: "Grün",
    optionC: "Schwarz",
    optionD: "Blau",
    answer: "B",
    word: "Grün = Green",
  },
  {
    prompt: "Which of these means the color yellow in German?",
    optionA: "Gelb",
    optionB: "Lila",
    optionC: "Braun",
    optionD: "Schwarz",
    answer: "A",
    word: "Gelb = Yellow",
  },
  {
    prompt: "Which of these means the color black in German?",
    optionA: "Schwarz",
    optionB: "Grün",
    optionC: "Blau",
    optionD: "Lila",
    answer: "A",
    word: "Schwarz = Black",
  },
  {
    prompt: "Which of these means the color red in German?",
    optionA: "Braun",
    optionB: "Blau",
    optionC: "Gelb",
    optionD: "Rot",
    answer: "D",
    word: "Rot = Red",
  },
  {
    prompt: "Which of these means the color white in German?",
    optionA: "Grün",
    optionB: "Rot",
    optionC: "weiß",
    optionD: "Schwarz",
    answer: "C",
    word: "weiß = White",
  },
  {
    prompt: "Which of these means the color purple in German?",
    optionA: "Gelb",
    optionB: "Blau",
    optionC: "Braun",
    optionD: "Lila",
    answer: "D",
    word: "Lila = Purple",
  },
  {
    prompt: "Which of these means the color blue in German?",
    optionA: "Blau",
    optionB: "Rot",
    optionC: "Schwarz",
    optionD: "Grün",
    answer: "A",
    word: "Blau = Blue",
  },
  {
    prompt: "Which of these means the color brown in German?",
    optionA: "Lila",
    optionB: "Braun",
    optionC: "Blau",
    optionD: "Gelb",
    answer: "B",
    word: "Braun = Brown",
  },
];
